<?php
/**
 * News-article structured data for episode pages (2026-10-09).
 *
 * AIOSEO's podcast post-type default is Article / NewsArticle, which gives each episode a NewsArticle node with
 * headline, author, dates and section. Two things Google's article guidance recommends were missing, and this
 * fills them in through AIOSEO's own `aioseo_schema_output` filter (no second JSON-LD block):
 *
 *   - image: the episode's own art (1200x630 first, then 16:9 and square), which hangs off the internal ng_episode
 *     post rather than the public post, so AIOSEO could not find it.
 *   - publisher: the SHOW (e.g. "Net Gain Edtech"), not the site-wide "Net Gain News" organization, with the
 *     show's publisher logo (show meta ng_publisher_logo_id, generated by pipeline/make_publisher_logo.py - a
 *     rectangular logo 60 px tall, per Google's article guidance). Net Gain News stays as parentOrganization.
 *
 * Nothing changes for an episode whose show has no publisher logo set: AIOSEO's default publisher is left alone.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Net_Gain_News_Schema {

	public static function register() {
		add_filter( 'aioseo_schema_output', array( __CLASS__, 'enrich_graph' ), 20 );
	}

	public static function enrich_graph( $graphs ) {
		if ( ! is_array( $graphs ) || ! is_singular( 'podcast' ) ) {
			return $graphs;
		}

		$episode_id = (int) get_post_meta( get_the_ID(), '_ng_source_episode_id', true );
		if ( ! $episode_id ) {
			return $graphs;
		}

		return self::apply( $graphs, self::context( $episode_id ) );
	}

	/** Everything the graph needs, read from WordPress: images, show name/url, logo. Pure data out. */
	private static function context( $episode_id ) {
		$context = array( 'images' => array(), 'show' => null );

		foreach ( array( 'ng_image_1200x630_id', 'ng_image_16x9_id', 'ng_image_square_id' ) as $key ) {
			$attachment_id = (int) get_post_meta( $episode_id, $key, true );
			$src           = $attachment_id ? wp_get_attachment_image_src( $attachment_id, 'full' ) : false;
			if ( $src ) {
				$context['images'][] = array( 'url' => $src[0], 'width' => (int) $src[1], 'height' => (int) $src[2] );
			}
		}

		$show_id = (int) wp_get_post_parent_id( $episode_id );
		$logo_id = $show_id ? (int) get_post_meta( $show_id, 'ng_publisher_logo_id', true ) : 0;
		$logo    = $logo_id ? wp_get_attachment_image_src( $logo_id, 'full' ) : false;
		if ( $show_id && $logo ) {
			$terms = get_the_terms( get_the_ID(), 'series' );
			$slug  = ( ! empty( $terms ) && ! is_wp_error( $terms ) ) ? $terms[0]->slug : '';
			$page  = $slug ? get_page_by_path( $slug ) : null;

			$context['show'] = array(
				'slug' => $slug ? $slug : (string) get_post_field( 'post_name', $show_id ),
				'name' => get_the_title( $show_id ),
				'url'  => $page ? get_permalink( $page ) : home_url( '/' ),
				'logo' => array( 'url' => $logo[0], 'width' => (int) $logo[1], 'height' => (int) $logo[2] ),
			);
		}

		return $context;
	}

	/**
	 * Pure: add image and publisher to every NewsArticle node in the graph.
	 * $context = array( 'images' => list of array(url,width,height), 'show' => null|array(slug,name,url,logo) ).
	 */
	public static function apply( array $graphs, array $context ) {
		$show_node = null;
		if ( ! empty( $context['show'] ) ) {
			$show        = $context['show'];
			$show_node   = array(
				'@type'              => 'Organization',
				'@id'                => home_url( '/#show-' . $show['slug'] ),
				'name'               => $show['name'],
				'url'                => $show['url'],
				'logo'               => self::image_object( $show['logo'], home_url( '/#show-' . $show['slug'] . '-logo' ) ),
				'parentOrganization' => array( '@id' => home_url( '/#organization' ) ),
			);
		}

		$touched = false;
		foreach ( $graphs as $i => $node ) {
			if ( ! is_array( $node ) || ! self::is_news_article( $node ) ) {
				continue;
			}
			if ( ! empty( $context['images'] ) ) {
				$node['image'] = array_map( array( __CLASS__, 'image_object' ), $context['images'] );
			}
			if ( $show_node ) {
				$node['publisher'] = array( '@id' => $show_node['@id'] );
				$touched           = true;
			}
			$graphs[ $i ] = $node;
		}

		if ( $touched && $show_node ) {
			$graphs[] = $show_node;
		}

		return $graphs;
	}

	private static function is_news_article( array $node ) {
		$type = isset( $node['@type'] ) ? $node['@type'] : '';
		return in_array( 'NewsArticle', (array) $type, true );
	}

	private static function image_object( array $image, $id = null ) {
		$object = array(
			'@type'  => 'ImageObject',
			'url'    => $image['url'],
			'width'  => $image['width'],
			'height' => $image['height'],
		);
		if ( $id ) {
			$object['@id'] = $id;
		}
		return $object;
	}
}
