<?php
/**
 * News-article structured data for episode pages (2026-10-09, revised 2026-10-10).
 *
 * AIOSEO's podcast post-type default is Article / NewsArticle, which gives each episode a NewsArticle node with
 * headline, author, dates and section. Two things Google's article guidance recommends were missing, and this
 * fills them in through AIOSEO's own `aioseo_schema_output` filter (no second JSON-LD block):
 *
 *   - image: the episode's own art (1200x630 first, then 16:9 and square), which hangs off the internal ng_episode
 *     post rather than the public post, so AIOSEO could not find it.
 *   - publisher logo: the publisher is the SITE's organization ("Net Gain News"), not the individual show - Google
 *     News keys a publication to the website and names it from the site name, so the sitemap, the publisher and
 *     the site name all agree. The show stays visible as the NewsArticle's articleSection and the episode's
 *     PodcastSeries. If AIOSEO's Organization node has no logo of its own (Search Appearance > Organization logo),
 *     the logo from the show's "Publisher logo" setting (show meta ng_publisher_logo_id, generated by
 *     pipeline/make_publisher_logo.py) is added to it.
 *
 * The BreadcrumbList is rewritten to Home > show > Episodes > episode (see context()).
 *
 * Nothing changes for an episode without art or a logo setting.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Net_Gain_News_Schema {

	public static function register() {
		add_filter( 'aioseo_schema_output', array( __CLASS__, 'enrich_graph' ), 20 );
	}

	public static function enrich_graph( $graphs ) {
		if ( ! is_array( $graphs ) || ! is_singular( 'podcast' ) ) {
			return $graphs;
		}

		$episode_id = (int) get_post_meta( get_the_ID(), '_ng_source_episode_id', true );
		if ( ! $episode_id ) {
			return $graphs;
		}

		return self::apply( $graphs, self::context( $episode_id ) );
	}

	/** Everything the graph needs, read from WordPress: the episode's images and the publisher logo. Pure data out. */
	private static function context( $episode_id ) {
		$context = array( 'images' => array(), 'logo' => null, 'breadcrumbs' => array() );

		foreach ( array( 'ng_image_1200x630_id', 'ng_image_16x9_id', 'ng_image_square_id' ) as $key ) {
			$attachment_id = (int) get_post_meta( $episode_id, $key, true );
			$src           = $attachment_id ? wp_get_attachment_image_src( $attachment_id, 'full' ) : false;
			if ( $src ) {
				$context['images'][] = array( 'url' => $src[0], 'width' => (int) $src[1], 'height' => (int) $src[2] );
			}
		}

		// Breadcrumbs: Home > the show > Episodes > this episode. AIOSEO's own trail points at the /podcast/ and
		// /series/ archive pages, which are duplicates of the show and episode list pages and are kept out of search.
		$terms = get_the_terms( get_the_ID(), 'series' );
		$term  = ( ! empty( $terms ) && ! is_wp_error( $terms ) ) ? $terms[0] : null;
		if ( $term ) {
			$show_page     = get_page_by_path( $term->slug );
			$episodes_page = get_page_by_path( $term->slug . '/episodes' );
			if ( $show_page && $episodes_page ) {
				$context['breadcrumbs'] = array(
					array( 'name' => 'Home', 'url' => home_url( '/' ) ),
					array( 'name' => $term->name, 'url' => get_permalink( $show_page ) ),
					array( 'name' => 'Episodes', 'url' => get_permalink( $episodes_page ) ),
					array( 'name' => html_entity_decode( get_the_title(), ENT_QUOTES, 'UTF-8' ), 'url' => '' ),
				);
			}
		}

		$show_id = (int) wp_get_post_parent_id( $episode_id );
		$logo_id = $show_id ? (int) get_post_meta( $show_id, 'ng_publisher_logo_id', true ) : 0;
		$logo    = $logo_id ? wp_get_attachment_image_src( $logo_id, 'full' ) : false;
		if ( $logo ) {
			$context['logo'] = array( 'url' => $logo[0], 'width' => (int) $logo[1], 'height' => (int) $logo[2] );
		}

		return $context;
	}

	/**
	 * Pure: add image to every NewsArticle node, and a logo to the site Organization node when it has none.
	 * $context = array( 'images' => list of array(url,width,height), 'logo' => null|array(url,width,height) ).
	 */
	public static function apply( array $graphs, array $context ) {
		$organization_id = home_url( '/#organization' );

		foreach ( $graphs as $i => $node ) {
			if ( ! is_array( $node ) ) {
				continue;
			}

			if ( isset( $node['@type'] ) && 'BreadcrumbList' === $node['@type'] && ! empty( $context['breadcrumbs'] ) ) {
				$items = array();
				foreach ( array_values( $context['breadcrumbs'] ) as $position => $crumb ) {
					$item = array( '@type' => 'ListItem', 'position' => $position + 1, 'name' => $crumb['name'] );
					if ( '' !== $crumb['url'] ) {
						$item['item'] = $crumb['url'];
					}
					$items[] = $item;
				}
				$node['itemListElement'] = $items;
				$graphs[ $i ]            = $node;
			}

			if ( self::is_news_article( $node ) && ! empty( $context['images'] ) ) {
				$node['image'] = array_map( array( __CLASS__, 'image_object' ), $context['images'] );
				$graphs[ $i ]  = $node;
			}

			if ( isset( $node['@id'], $node['@type'] ) && $organization_id === $node['@id'] && 'Organization' === $node['@type']
				&& empty( $node['logo'] ) && ! empty( $context['logo'] ) ) {
				$node['logo'] = self::image_object( $context['logo'], home_url( '/#organization-logo' ) );
				$graphs[ $i ] = $node;
			}
		}

		return $graphs;
	}

	private static function is_news_article( array $node ) {
		$type = isset( $node['@type'] ) ? $node['@type'] : '';
		return in_array( 'NewsArticle', (array) $type, true );
	}

	private static function image_object( array $image, $id = null ) {
		$object = array(
			'@type'  => 'ImageObject',
			'url'    => $image['url'],
			'width'  => $image['width'],
			'height' => $image['height'],
		);
		if ( $id ) {
			$object['@id'] = $id;
		}
		return $object;
	}
}
